### ISSUE TITLE
[ci] Include LocaleSelection.swift in the OigoCore Xcode target

### ISSUE THREAD

**Issue by douglasjarquin** [douglasjarquin/oigo#123]
`main` verify is red because the Xcode source-membership gate rejects a production file that exists on disk.

## Problem

`Sources/OigoCore/LocaleSelection.swift` is in the tree and compiled by SwiftPM, but it is not a member of the `OigoCore` Xcode target.

`Scripts/check-xcode-source-membership.py` fails with:

```text
FAIL: every production source is compiled into the correct Xcode target:
OigoCore missing from Xcode target: Sources/OigoCore/LocaleSelection.swift
```

This is the same failure on `main` after merging #120 and after merging #122.

Observed runs:

- https://github.com/douglasjarquin/oigo/actions/runs/32333155499 (`main` after #120)
- https://github.com/douglasjarquin/oigo/actions/runs/32334387086 (`main` after #122)

Feature-branch SwiftPM jobs can still pass, so this is an Xcode-project drift bug, not a Swift compile error.

## Intended outcome

Every file under `Sources/OigoCore/` is compiled into the `OigoCore` Xcode target.

`swift run oigo-macos-floor-check` is green on `main`.

The membership check stays as a required gate so this class of miss cannot ship again.

## Related

#101 added the macOS 26 floor and real-bundle CI.
The membership check is doing its job; the pbxproj was not updated when `LocaleSelection.swift` landed.

**Comment by douglasjarquin** [comment]
LocaleSelection.swift is already a member of the OigoCore Xcode target on current `main` (`B41` / `A4E`), landed with the locale/capture work and present after #126.

`swift run oigo-macos-floor-check` and `Scripts/check-xcode-source-membership.py` are GREEN on `874755e6`.

Closing as already fixed.
